services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./caddy-config/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-config/snippets.caddy:/etc/caddy/snippets.caddy
      - ./caddy-config/sites:/etc/caddy/sites
      - ./caddy-data:/data
      - ./caddy-config/pages:/usr/share/caddy/pages

  cpm:
    image: ghcr.io/tomaszmek/cpm:latest
    # Or build locally:
    # build: .
    container_name: cpm
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - CONTAINER_NAME=caddy
      - CADDY_CONFIG_PATH=/caddy-config
      - CADDY_DATA_PATH=/caddy-data
    volumes:
      - ./caddy-config:/caddy-config
      - ./caddy-data:/caddy-data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy
